services:
  next_app:
    image: next-app
    build:
      context: ./my-next-app/
      dockerfile: Dockerfile.dev
      ### 開発用を読み込み ###
    container_name: next_app
    ports:
      - "3000:3000"
    volumes:
      - ./my-next-app:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next_app
