server {
    listen 80;

		# "/"にアクセスされた場合の処理
    location / {
        proxy_pass http://next_app:3000; # バックエンド(Next.js)のポートに転送
        proxy_http_version 1.1; #
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
		### 追加すべき処理 ###
		# HTTPS(SSL)がない
		# 真因のIPアドレスが特定できない(どのサーバーが原因か分からない)
		# タイムアウト設定がデフォルトのままで短い(バックエンド遅延した時にすぐにエラー扱いになる)
		# 静的ファイルはNginxでキャッシュできるようにする(今は一旦バックエンドを経由して配信)
}

# メモ：nginxはリバースプロキシとし動作する。（クライアント → Nginx → 各サーバー）
# NginxがSSL(暗号化処理)を引き受けることで、わざわざ各サーバーでSSL化する必要がなくなる。
# 外部からはNginxのIPアドレスしか分からないので直接攻撃のターゲットになることを防げる。

# webSocketって何？